import Head from "next/head";
import Navbar from "./components/Navbar";
import {
  BsHandThumbsUp,
  BsFillPuzzleFill,
  BsEmojiSmile,
  BsFillMoonStarsFill,
  BsSunFill,
} from "react-icons/bs";
import {
  AiFillFacebook,
  AiFillGithub,
  AiFillInstagram,
  AiFillMail,
  AiOutlineLaptop,
} from "react-icons/ai";
import Image from "next/image";
import { useEffect, useState } from "react";
import { TypeAnimation } from "react-type-animation";
import { motion, useScroll } from "framer-motion";
import Banner from "./Banner";
import Portfolio from "./components/Portfolio";
import MainBanner from "./components/MainBanner";
import SkillBanner from "./components/SkillBanner";

export default function Home() {
  const [darkMode, SetDarkMode] = useState(false);
  const [loader, setLoader] = useState(true);

  const { scrollYProgress } = useScroll();

  useEffect(() => {
    setTimeout(() => {
      setLoader(false);
    }, 3000);
  }, []);

  return (
    <div className={darkMode ? "dark" : ""}>
      {loader ? (
        <div className="bg-teal-950 flex h-screen text-center ">
          <TypeAnimation
            sequence={["Welcome To My Personal Website", 1000]}
            speed={25}
            repeat={Infinity}
            wrapper="span"
            className="font-RalewayThin text-xl text-white font-bold m-auto"
          />
          <div className="fixed top-0 right-0 h-screen w-screen z-50 flex justify-center items-center">
            <div className="animate-spin rounded-full h-32 w-32 border-t-2 border-b-2 border-gray-300"></div>
          </div>
        </div>
      ) : (
        <div>
          <Head>
            <title>Khant Min Kyi</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className="bg-gradient-to-br dark:from-teal-800 dark:to-teal-900 ">
            {/* navbar */}
            <Navbar
              SetDarkMode={SetDarkMode}
              darkMode={darkMode}
              BsFillMoonStarsFill={BsFillMoonStarsFill}
              BsSunFill={BsSunFill}
            />
            {/* Main Banner */}
            <MainBanner
              motion={motion}
              AiFillFacebook={AiFillFacebook}
              AiFillGithub={AiFillGithub}
              AiFillInstagram={AiFillInstagram}
              AiFillMail={AiFillMail}
              TypeAnimation={TypeAnimation}
              Image={Image}
            />
            {/* About Section */}
            <section id="about">
              <div className="text-center  min-h-50">
                <h1 className=" flex justify-center text-xl md:text-2xl font-RalewayItalic py-5 text-teal-500">
                  About Me <BsHandThumbsUp className="mx-2" />
                </h1>
                <div className="grid md:grid-cols-2 text-center my-6">
                  <div className="my-6 mx-12">
                    <h1 className="text-xl font-RalewaySemiBold mb-6 dark:text-gray-300">
                      Experience
                    </h1>
                    <ul className="list-none font-RalewayThin font-semibold max-w-lg mx-auto dark:text-gray-300">
                      <li className=" justify-center items-center p-2 text-sm">
                        Since 2020 Starting Working as Freelancer for small
                        Local Projects.
                      </li>

                      <TypeAnimation
                        sequence={[
                          " From , I StartWorking In MAVEN Technology Software Hosue as Full-Stack Web Developer. Developing Many Wordpress Site and Laravel Websites.",
                          2000,
                          "Develop a Laravel And React Website as a Freelancer.",
                          2000,
                        ]}
                        speed={70}
                        repeat={Infinity}
                        wrapper="span"
                        className="justify-center items-center p-2 text-sm mt-10 dark:text-white"
                      />
                    </ul>
                  </div>
                  <div className="text-center my-6">
                    <h1 className="font-RalewaySemiBold text-xl mb-6 dark:text-gray-300">
                      Education
                    </h1>
                    <h4 className="font-RalewayThin font-semibold mb-6 dark:text-gray-200">
                      BEHS No(1) Dagon
                    </h4>
                    <h4 className="font-RalewayThin font-semibold mb-6 dark:text-gray-200">
                      BE IT at Technological University Thanlyin
                    </h4>
                  </div>
                </div>
              </div>
            </section>
            {/* Skill Section */}
            <SkillBanner motion={motion} Image={Image} />

            {/* Banner Section */}
            <section>
              <div
                style={{ height: "375px", overflowY: "scroll" }}
                className="bannerDiv"
              >
                <Banner className="bg-teal-100 dark:bg-teal-950">
                  <div className="my-auto dark:text-white">
                    <h1 className="text-4xl font-RalewayBold mt-10">
                      Team <b className="text-teal-400"> Work</b>
                    </h1>
                    <h6 className="font-RalewayItalic text-lg mt-10">
                      Love To Work Group Projects . Actively Participate With
                      Team
                    </h6>
                    <h5 className="flex gap-4 items-center text-xl font-RalewayBold mt-10">
                      Active Coder <AiOutlineLaptop />
                    </h5>
                  </div>
                </Banner>
                <Banner className="bg-teal-400 dark:bg-gray-950">
                  <div className="my-auto dark:text-gray-50">
                    <h1 className="text-4xl font-RalewayBold mt-10">
                      Brain
                      <b className="text-teal-100 dark:text-teal-300">
                        Storming
                      </b>
                    </h1>
                    <h6 className="font-RalewayItalic text-lg mt-10">
                      As a Backend Coder , Would Love To Think And Make
                      <b className="text-white dark:text-teal-300">
                        A New Systematic and Creative Idea
                      </b>
                      For Development
                    </h6>
                    <h5 className="flex gap-4 items-center text-xl font-RalewayBold mt-10">
                      Systematic Engineer <BsFillPuzzleFill />
                    </h5>
                  </div>
                </Banner>
                <Banner className="bg-teal-200 dark:bg-emerald-950">
                  <div className="my-auto dark:text-gray-100">
                    <h1 className="text-3xl font-RalewayBold mt-10">
                      Progressive
                      <b className="text-lime-800 dark:text-lime-300">
                        Learning
                      </b>
                    </h1>
                    <h6 className="font-RalewayItalic text-md mt-10">
                      I'm A Progressive Learner !{" "}
                      <b className="text-teal-800 dark:text-lime-200">
                        Explore , Research , Creative .
                      </b>
                    </h6>
                    <h5 className="flex gap-4 items-center text-xl font-RalewayBold mt-10">
                      Flexible Developer <BsEmojiSmile />
                    </h5>
                  </div>
                </Banner>
              </div>
            </section>
            {/* Portfolio */}
            <Portfolio motion={motion} Image={Image} />
          </main>
          <motion.div
            className="progress-bar"
            style={{ scaleX: scrollYProgress }}
          />
          <footer className="bg-gray-50 dark:bg-teal-800">
            <div className="text-center">
              <h1 className="font-RalewayThin text-xl md:text-2xl py-10 md:py-14 dark:text-teal-500">
                Developed By KMK{" "}
              </h1>
            </div>
          </footer>
        </div>
      )}
    </div>
  );
}
